---
apiVersion: v2
name: vector-element
description: |
  Element (formerly known as Vector and Riot) is a Matrix web client built using the Matrix React SDK.
icon: https://element.io/images/element-logo.svg
home: https://github.com/vector-im/element-web/
#ChartVersion
version: 0.1.4
# MatrixVersion
appVersion: v1.11.0
type: application

maintainers:
  - name: 0hlov3
    email: 0hlov3@protonmail.com
    url: https://schoenwald.me