apiVersion: v2
name: pinafore
description: Pinafore is an an alternative web client for Mastodon, focused on speed and simplicity.

icon: https://raw.githubusercontent.com/nolanlawson/pinafore/master/src/static/sailboat-icon.svg
home: https://github.com/nolanlawson/pinafore

type: application
# Chart Version
version: "0.0.6"
# gotosocial version
appVersion: "v2.2.1"

maintainers:
  - name: 0hlov3
    email: 0hlov3@protonmail.com
    url: https://schoenwald.me