apiVersion: v2
name: privatebin
description: PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data.
icon: https://privatebin.info/img/logo.png
home: https://github.com/PrivateBin/PrivateBin


type: application
# Chart Version
version: 0.1.3
# Privatebin Version
appVersion: "1.4.0"

maintainers:
  - name: 0hlov3
    email: 0hlov3@protonmail.com
    url: https://schoenwald.me